default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
cure-mikan: styles/cure-mikan.scss
cure-yuzuha: styles/cure-yuzuha.scss
cure-ayame: styles/cure-ayame.scss
cure-kureha: styles/cure-kureha.scss
juliamo-mastodon-light: styles/juliamo-mastodon-light.scss
